# Streamlit secrets for deployment
# Add your API keys here when deploying to Streamlit Cloud

[secrets]
EXA_API_KEY = "your_exa_api_key_here"
GOOGLE_API_KEY = "your_google_api_key_here"
GROQ_API_KEY = "your_groq_api_key_here"
