# Streamlit secrets for deployment
# Add your API keys here when deploying to Streamlit Cloud

# Streamlit Cloud Secrets Configuration
# Copy this template and add your actual API keys

[secrets]
EXA_API_KEY = "your-exa-api-key-here"
GOOGLE_API_KEY = "your-google-api-key-here"

# Optional: For debugging
# STREAMLIT_ENV = "cloud"
GROQ_API_KEY = "your_groq_api_key_here"
